CREATE DATABASE IF NOT EXISTS detrandb;

USE detrandb;

CREATE TABLE MOTORISTA (
	cpf BIGINT(11) UNSIGNED NOT NULL,
	nome VARCHAR(80) NOT NULL,
	dataVencimento DATE NOT NULL,
	categoriaCNH ENUM('A', 'B', 'AB') NOT NULL,
	CONSTRAINT MOTORISTA_PK PRIMARY KEY(cpf),
	CHECK MOTORISTA_CK CHECK(DATEDIFF(dataVencimento, NOW()) < 1 )
) ENGINE=InnoDB;

CREATE TABLE VEICULO (
	placa CHAR(7) NOT NULL,
	cpf BIGINT(11) UNSIGNED NOT NULL,
	marca VARCHAR(50) NOT NULL,
	modelo VARCHAR(50) NOT NULL,
	ano SMALLINT UNSIGNED NOT NULL,
	corPredominante VARCHAR(20) NOT NULL,
	CONSTRAINT VEICULO_PK PRIMARY KEY(placa),
	CONSTRAINT VEICULO_MOTORISTA_FK FOREIGN KEY (cpf)
		REFERENCES MOTORISTA (cpf)
		ON UPDATE CASCADE
		ON DELETE RESTRICT;
) ENGINE=InnoDB;

CREATE TABLE TIPOMULTA (
	idTipoMulta INT UNSIGNED NOT NULL AUTO_INCREMENT,
	descricao VARCHAR(80) NOT NULL
	CONSTRAINT TIPOMULTA_PK PRIMARY KEY (idTipoMulta),
) ENGINE=InnoDB AUTO_INCREMENT=1;

CREATE TABLE MULTA (
	idMulta INT UNSIGNED NOT NULL AUTO_INCREMENT,
	placa CHAR(7) NOT NULL,
	tipoInfracao INT UNSIGNED NOT NULL,
	valor DECIMAL(6,2) NOT NULL,
	dataMulta DATE NOT NULL,
	pontosPenalidade TINYINT UNSIGNED DEFAULT 0,
	CONSTRAINT MULTA_PK PRIMARY KEY (idMulta),
	CONSTRAINT MULTA_VEICULO_FK FOREIGN KEY (placa)
		REFERENCES VEICULO (placa)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	CONSTRAINT MULTA_TIPOMULTA_FK FOREIGN KEY (tipoInfracao)
		REFERENCES TIPOMULTA (idTipoMulta)
		ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1;
